"""
forge_tools.py — Capability Forge: the agent extends ITSELF at runtime.

This is the headline feature: when the agent meets a task no existing tool can
do, it can WRITE a brand-new Python tool, the Forge validates and registers it
LIVE, and the agent uses it in the same breath — and it persists forever.

How it works (the part that impresses):
  1. The model supplies a name + a complete Python `@tool` function.
  2. forge_tool() validates it (must compile, must define exactly one @tool, runs
     a safety scan), writes it to tools/dynamic/<name>.py.
  3. It imports the module, extracts the BaseTool, and registers it into the LIVE
     registry — nodes.TOOL_MAP IS the same dict, so the worker can execute it now.
  4. It refreshes the LLM↔tools binding so the model can *choose* to call it too.
  5. Because it lives in tools/dynamic/, the registry auto-loads it on every future
     startup. The agent literally grows new permanent abilities by itself.

Tools:
  • forge_tool(tool_name, description, python_code)  — create & register a tool
  • list_forged_tools()                              — list self-created tools
  • inspect_forged_tool(tool_name)                   — show a forged tool's source
  • remove_forged_tool(tool_name)                    — delete a forged tool
"""
from __future__ import annotations

import ast
import importlib
import os
import re
from pathlib import Path
from typing import Annotated

from langchain_core.tools import tool

_DYN_DIR = Path(__file__).resolve().parent / "dynamic"

# Patterns that are dangerous even on a trusted local machine. The agent runs
# unrestricted by the user's choice, but the Forge still refuses the few things
# that would corrupt the agent itself or wipe the disk wholesale.
_HARD_BLOCK = [
    r"\bshutil\.rmtree\s*\(\s*['\"]?[A-Za-z]:[\\/]",   # rmtree of a drive root
    r"format\s+[A-Za-z]:",                              # format C:
    r"os\.remove\(\s*__file__",                         # self-deletion games
    r"while\s+True\s*:\s*(#.*)?$",                       # bare infinite loop
]


def _valid_identifier(name: str) -> bool:
    return bool(re.fullmatch(r"[a-z][a-z0-9_]{2,40}", name))


def _scan_safety(code: str) -> str | None:
    for pat in _HARD_BLOCK:
        if re.search(pat, code, re.MULTILINE):
            return f"رُفض الكود: نمط خطير ({pat}) قد يُتلف النظام نفسه."
    return None


def _extract_tool_function_name(code: str) -> str | None:
    """Find a function decorated with @tool. Returns its name or None."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for dec in node.decorator_list:
                dname = (dec.id if isinstance(dec, ast.Name)
                         else (dec.func.id if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Name)
                               else (dec.attr if isinstance(dec, ast.Attribute) else "")))
                if dname == "tool":
                    return node.name
    return None


_HEADER = (
    "# Auto-generated by the HAYO Capability Forge.\n"
    "# The agent created this tool for itself at runtime.\n"
    "from __future__ import annotations\n"
    "from typing import Annotated\n"
    "from langchain_core.tools import tool\n\n\n"
)


@tool
def forge_tool(
    tool_name: Annotated[str, "snake_case name for the new tool, e.g. 'text_to_morse'. Must be unique."],
    description: Annotated[str, "One line describing what the tool does (for logs/listing)."],
    python_code: Annotated[str, "Complete Python defining ONE @tool function named exactly tool_name. "
                                "It MAY 'from ... import' inside the function. Must return a string."],
) -> str:
    """🔥 اصنع أداة جديدة للوكيل وقت التشغيل وسجّلها فوراً (Capability Forge).

    استخدمها عندما لا توجد أي أداة قادرة على إنجاز المهمة: اكتب دالة Python مزخرفة
    بـ @tool باسم tool_name نفسه، وستُضاف للوكيل حيّاً وتبقى دائمة.

    قواعد كتابة python_code:
      • يجب أن تحتوي: @tool ثم def {tool_name}(...) -> str
      • أعِد نصاً دائماً (str)، وعالج الأخطاء داخل try/except
      • ضع أي استيرادات (import) داخل الدالة لتجنّب مشاكل التحميل
    مثال python_code:
        @tool
        def days_until(date_str: str) -> str:
            \"\"\"احسب عدد الأيام حتى تاريخ بصيغة YYYY-MM-DD.\"\"\"
            from datetime import date
            y,m,d = map(int, date_str.split('-'))
            return f"باقٍ {(date(y,m,d)-date.today()).days} يوم"
    """
    if not _valid_identifier(tool_name):
        return ("❌ اسم غير صالح. استخدم snake_case (أحرف صغيرة وأرقام و_)، "
                "يبدأ بحرف، 3–41 خانة.")

    # don't clobber a built-in tool
    try:
        from tools.registry import TOOLS_BY_NAME
        if tool_name in TOOLS_BY_NAME and not (_DYN_DIR / f"{tool_name}.py").exists():
            return f"❌ '{tool_name}' اسم أداة مدمجة بالفعل — اختر اسماً آخر."
    except Exception:
        pass

    # safety scan
    danger = _scan_safety(python_code)
    if danger:
        return f"❌ {danger}"

    # the code must define a @tool function with the SAME name
    fn_name = _extract_tool_function_name(python_code)
    if fn_name is None:
        return ("❌ لم أجد دالة مزخرفة بـ @tool في الكود. "
                "اكتب: @tool ثم def بنفس الاسم وترجع str.")
    if fn_name != tool_name:
        return f"❌ اسم الدالة '{fn_name}' لا يطابق tool_name '{tool_name}'. وحّدهما."

    # must compile
    full = _HEADER + python_code.strip() + "\n"
    try:
        compile(full, f"<forge:{tool_name}>", "exec")
    except SyntaxError as e:
        return f"❌ خطأ نحوي في الكود: {e}"

    # write + import + register
    _DYN_DIR.mkdir(exist_ok=True)
    (_DYN_DIR / "__init__.py").touch(exist_ok=True)
    target = _DYN_DIR / f"{tool_name}.py"
    target.write_text(full, encoding="utf-8")

    try:
        modname = f"tools.dynamic.{tool_name}"
        if modname in list(importlib.sys.modules):
            del importlib.sys.modules[modname]
        module = importlib.import_module(modname)
    except Exception as e:
        target.unlink(missing_ok=True)
        return f"❌ فشل تحميل الأداة: {type(e).__name__}: {e}"

    from langchain_core.tools import BaseTool
    new_tool = next((v for v in vars(module).values()
                     if isinstance(v, BaseTool) and v.name == tool_name), None)
    if new_tool is None:
        target.unlink(missing_ok=True)
        return "❌ لم يُعثر على كائن الأداة بعد التحميل (تأكد أن الاسم مطابق)."

    try:
        from tools.registry import register_tool
        register_tool(new_tool)
        # make the model able to CHOOSE it immediately
        from agent import nodes as _nodes
        if hasattr(_nodes, "refresh_tool_binding"):
            _nodes.refresh_tool_binding()
    except Exception as e:
        return f"⚠️ سُجّلت الأداة جزئياً لكن تعذّر تحديث الربط: {e}"

    return (f"🔥 تم صَهر أداة جديدة وتسجيلها حيّاً: «{tool_name}»\n"
            f"   الوصف: {description}\n"
            f"   الحالة: متاحة الآن للاستخدام فوراً، ومحفوظة دائماً في tools/dynamic/.\n"
            f"   استدعِها مباشرةً كأي أداة أخرى.")


@tool
def list_forged_tools() -> str:
    """عرض الأدوات التي صنعها الوكيل لنفسه (الموجودة في tools/dynamic/)."""
    _DYN_DIR.mkdir(exist_ok=True)
    files = sorted(p.stem for p in _DYN_DIR.glob("*.py") if not p.stem.startswith("_"))
    if not files:
        return "🛠️ لا توجد أدوات مُصنّعة بعد. اصنع واحدة بـ forge_tool()."
    lines = [f"🛠️ الأدوات المُصنّعة ذاتياً ({len(files)}):"]
    for f in files:
        first_doc = ""
        try:
            src = (_DYN_DIR / f"{f}.py").read_text(encoding="utf-8")
            m = re.search(r'"""(.+?)"""', src, re.S)
            if m:
                first_doc = m.group(1).strip().splitlines()[0]
        except Exception:
            pass
        lines.append(f"  • {f}" + (f" — {first_doc}" if first_doc else ""))
    return "\n".join(lines)


@tool
def inspect_forged_tool(tool_name: Annotated[str, "Name of a forged tool."]) -> str:
    """عرض الكود المصدري لأداة مُصنّعة (للمراجعة/التعديل)."""
    target = _DYN_DIR / f"{tool_name}.py"
    if not target.exists():
        return f"❌ لا توجد أداة مُصنّعة باسم '{tool_name}'."
    code = target.read_text(encoding="utf-8")
    return f"📄 مصدر «{tool_name}»:\n```python\n{code}\n```"


@tool
def remove_forged_tool(tool_name: Annotated[str, "Name of the forged tool to delete."]) -> str:
    """حذف أداة مُصنّعة (من السجل الحيّ ومن القرص)."""
    target = _DYN_DIR / f"{tool_name}.py"
    if not target.exists():
        return f"❌ لا توجد أداة مُصنّعة باسم '{tool_name}'."
    try:
        from tools.registry import unregister_tool
        unregister_tool(tool_name)
        from agent import nodes as _nodes
        if hasattr(_nodes, "refresh_tool_binding"):
            _nodes.refresh_tool_binding()
    except Exception:
        pass
    target.unlink(missing_ok=True)
    return f"🗑️ حُذفت الأداة المُصنّعة «{tool_name}»."
